export enum ErrorCode {
  WrongEmailOrPassword = 'WRONG_EMAIL_OR_PASSWORD',
  DuplicatedEmail = 'DUPLICATED_EMAIL',
  InvalidToken = 'INVALID_TOKEN',
  ExpiredToken = 'EXPIRED_TOKEN',
  InvalidQrCode = 'INVALID_QR_CODE',
  ExceedFarmCount = 'EXCEED_FARM_COUNT',
  FarmNotFound = 'FARM_NOT_FOUND',
  InvalidInvitationCode = 'INVALID_INVITATION_CODE',
  ForbiddenPermission = 'FORBIDDEN_PERMISSION',
  RoleProtected = 'ROLE_PROTECTED',
  RoleNotFound = 'ROLE_NOT_FOUND',
  InvitationDuplicated = 'INVITATION_DUPLICATED',
  MemberNotFound = 'MEMBER_NOT_FOUND',
  MemberProtected = 'MEMBER_PROTECTED',
}
