export const ROUTES = {
  login: '/login',
  register: '/register',
  home: '/',
  attendance: '/attendance',
  attendanceQrCode: '/attendance/qrcode',
  profile: '/profile',
  menu: '/menu',
  scan: '/scan',
  me: '/me',
  farms: '/farms',
  members: '/members',
  roles: '/roles',
  invitation: '/invitation',
  invitationAccept: '/invitation/accept',
} as const;
